### ISSUE TITLE
ngr: Task 'install' not found in root project 'java-spring'.

### ISSUE THREAD

**Issue by amotl** [pyveci/pueblo#24]
## Problem

When running `ngr test java-spring` for https://github.com/crate/crate-sample-apps/tree/main/java-spring, it fails. Apparently, this Gradle project has no `install` target.

## Details
```shell
(.venv) sink:crate-sample-apps amo$ ngr test java-spring/
[...]
2023-11-22 18:08:27,611 [root                      ] INFO    : Probing: type=ItemType.JAVA, class=<class 'pueblo.ngr.runner.JavaRunner'>
2023-11-22 18:08:27,612 [root                      ] INFO    : Invoking JAVA in directory: java-spring
2023-11-22 18:08:27,612 [root                      ] INFO    : Environment Information
2023-11-22 18:08:27,612 [root                      ] INFO    : Running command: java -version
java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)
2023-11-22 18:08:27,792 [root                      ] INFO    : Installing
2023-11-22 18:08:27,792 [root                      ] INFO    : Running command: ./gradlew install

FAILURE: Build failed with an exception.

* What went wrong:
Task 'install' not found in root project 'java-spring'.

* Try:
> Run gradlew tasks to get a list of available tasks.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 478ms
Traceback (most recent call last):
  File "/Users/amo/dev/crate/docs/crate-sample-apps/.venv/bin/ngr", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/amo/dev/crate/docs/crate-sample-apps/.venv/lib/python3.11/site-packages/pueblo/ngr/cli.py", line 56, in main
    run(args.target, args.__dict__)
  File "/Users/amo/dev/crate/docs/crate-sample-apps/.venv/lib/python3.11/site-packages/pueblo/ngr/core.py", line 120, in run
    return ngr.run()
           ^^^^^^^^^
  File "/Users/amo/dev/crate/docs/crate-sample-apps/.venv/lib/python3.11/site-packages/pueblo/ngr/core.py", line 108, in run
    self.runner.run()
  File "/Users/amo/dev/crate/docs/crate-sample-apps/.venv/lib/python3.11/site-packages/pueblo/ngr/runner.py", line 42, in run
    self.install()
  File "/Users/amo/dev/crate/docs/crate-sample-apps/.venv/lib/python3.11/site-packages/pueblo/ngr/runner.py", line 240, in install
    run_command("./gradlew install")
  File "/Users/amo/dev/crate/docs/crate-sample-apps/.venv/lib/python3.11/site-packages/pueblo/ngr/util.py", line 27, in run_command
    subprocess.check_call(shlex.split(command))  # noqa: S603
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./gradlew', 'install']' returned non-zero exit status 1.
```

**Comment by amotl** [comment]
This was fixed by GH-26.
